// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4sSD_PHC8akyDqAqgFf53cGZHqcaoFe4',
    appId: '1:290935986638:web:b63543b59e778b5d6db39f',
    messagingSenderId: '290935986638',
    projectId: 'studtappka',
    authDomain: 'studtappka.firebaseapp.com',
    storageBucket: 'studtappka.firebasestorage.app',
    measurementId: 'G-9LFMKHR855',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8WZLwo9Dhluhz2rD4euF5Ux8NjyoqoD0',
    appId: '1:290935986638:android:7bda67da00a8db066db39f',
    messagingSenderId: '290935986638',
    projectId: 'studtappka',
    storageBucket: 'studtappka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6SdjnqBi4ME5Chyls0XXN_uEcVstCdiQ',
    appId: '1:290935986638:ios:14e0f086c8faba466db39f',
    messagingSenderId: '290935986638',
    projectId: 'studtappka',
    storageBucket: 'studtappka.firebasestorage.app',
    iosBundleId: 'com.example.fluuterek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6SdjnqBi4ME5Chyls0XXN_uEcVstCdiQ',
    appId: '1:290935986638:ios:14e0f086c8faba466db39f',
    messagingSenderId: '290935986638',
    projectId: 'studtappka',
    storageBucket: 'studtappka.firebasestorage.app',
    iosBundleId: 'com.example.fluuterek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4sSD_PHC8akyDqAqgFf53cGZHqcaoFe4',
    appId: '1:290935986638:web:6ac5a112a9e20a116db39f',
    messagingSenderId: '290935986638',
    projectId: 'studtappka',
    authDomain: 'studtappka.firebaseapp.com',
    storageBucket: 'studtappka.firebasestorage.app',
    measurementId: 'G-Q3S16KW2X5',
  );
}
